# Includes for tests
require_relative '../lib/constants.rb'
require_relative '../lib/interface.rb'
require_relative '../lib/create.rb'
require_relative '../lib/db.rb'
require_relative '../lib/player.rb'
require_relative '../lib/match.rb'
require_relative '../lib/utils.rb'
require_relative '../lib/predicates.rb'
require_relative '../lib/speech.rb'
require_relative '../lib/set.rb'
require_relative '../lib/move.rb'
require_relative '../lib/wiz.rb'
require_relative '../lib/rob.rb'
require_relative '../lib/help.rb'
require_relative '../lib/look.rb'
require_relative '../lib/game.rb'
