# Includes for tests
require_relative '../lib/constants'
require_relative '../lib/interface'
require_relative '../lib/create'
require_relative '../lib/db'
require_relative '../lib/player'
require_relative '../lib/match'
require_relative '../lib/utils'
require_relative '../lib/predicates'
require_relative '../lib/speech'
require_relative '../lib/set'
require_relative '../lib/move'
require_relative '../lib/wiz'
require_relative '../lib/rob'
require_relative '../lib/help'
require_relative '../lib/look'
require_relative '../lib/game'
